---
platform: linux
image: docker:///boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-src-in
  - name: version-semver
outputs:
  - name: candidate
run:
  path: bosh-cpi-src-in/ci/tasks/build-candidate.sh
