---
platform: linux
image: docker:///boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-src-in
  - name: bosh-init
  - name: bosh-release
  - name: bosh-cpi-dev-artifacts
  - name: version-semver
  - name: stemcell
outputs:
  - name: bosh-director-deployment
run:
  path: bosh-cpi-src-in/ci/tasks/deploy-dynamic-networking.sh
params:
  bosh_admin_password:           replace-me
  dns:                           replace-me
  openstack_flavor:              replace-me
  openstack_connection_timeout:  replace-me
  openstack_read_timeout:        replace-me
  openstack_write_timeout:       replace-me
  openstack_state_timeout:       replace-me
  private_key_data:              replace-me
  bosh_registry_port:            replace-me
  bosh_openstack_ca_cert:        replace-me
  openstack_net_id:              replace-me
  openstack_security_group:      replace-me
  openstack_default_key_name:    replace-me
  openstack_auth_url:            replace-me
  openstack_username:            replace-me
  openstack_api_key:             replace-me
  openstack_tenant:              replace-me
  openstack_floating_ip:         replace-me
  time_server_1:                 replace-me
  time_server_2:                 replace-me
