---
platform: linux
image: docker:///boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-release
  - name: openstack-lifecycle-stemcell
run:
  path: bosh-cpi-release/ci/tasks/run-lifecycle.sh
params:
  BOSH_OPENSTACK_DOMAIN:              replace-me
  BOSH_OPENSTACK_AUTH_URL_V2:         replace-me
  BOSH_OPENSTACK_AUTH_URL_V3:         replace-me
  BOSH_OPENSTACK_USERNAME:            replace-me
  BOSH_OPENSTACK_API_KEY:             replace-me
  BOSH_OPENSTACK_USERNAME_V3:         replace-me
  BOSH_OPENSTACK_API_KEY_V3:          replace-me
  BOSH_OPENSTACK_TENANT:              replace-me
  BOSH_OPENSTACK_PROJECT:             replace-me
  BOSH_OPENSTACK_MANUAL_IP:           replace-me
  BOSH_OPENSTACK_NET_ID:              replace-me
  BOSH_CLI_SILENCE_SLOW_LOAD_WARNING: replace-me
  BOSH_OPENSTACK_VOLUME_TYPE:         replace-me
  BOSH_OPENSTACK_CONNECT_TIMEOUT:     replace-me
  BOSH_OPENSTACK_READ_TIMEOUT:        replace-me
  BOSH_OPENSTACK_WRITE_TIMEOUT:       replace-me
  BOSH_OPENSTACK_DEFAULT_KEY_NAME:    replace-me
  BOSH_OPENSTACK_CA_CERT:             replace-me
