---
platform: linux
image: docker:///bosh/openstack-cpi-release
inputs:
  - name: bosh-cpi-release
  - name: stemcell
  - name: bosh-concourse-ci
  - name: bats
run:
  path: bosh-cpi-release/ci/tasks/run-bats.sh
params:
  base_os:                              replace-me
  network_type_to_test:                 replace-me
  BAT_DIRECTOR:	                        replace-me
  BAT_DNS_HOST:	                        replace-me
  BAT_INFRASTRUCTURE:					replace-me
  BAT_NETWORKING:	                    replace-me
  BAT_VCAP_PASSWORD:	                replace-me
  BAT_STEMCELL:	                        replace-me
  BAT_DEPLOYMENT_SPEC:	                replace-me
  BAT_VCAP_PRIVATE_KEY:             	replace-me
  BOSH_OPENSTACK_AUTH_URL:	            replace-me
  BOSH_OPENSTACK_USERNAME:	            replace-me
  BOSH_OPENSTACK_API_KEY:	            replace-me
  BOSH_OPENSTACK_TENANT:	            replace-me
  BOSH_OPENSTACK_FLAVOR:	            replace-me
  BOSH_OPENSTACK_VIP_DIRECTOR_IP:	    replace-me
  BOSH_OPENSTACK_MICRO_NET_ID:  	    replace-me
  BOSH_OPENSTACK_NET_ID:	            replace-me
  BOSH_OPENSTACK_MANUAL_IP:	            replace-me
  BOSH_OPENSTACK_REGISTRY_PORT:     	replace-me
  BOSH_OPENSTACK_PRIVATE_KEY:	        replace-me
  BOSH_OPENSTACK_STATE_TIMEOUT:	        replace-me
  BOSH_OPENSTACK_CONNECTION_TIMEOUT:	replace-me
  BOSH_OPENSTACK_DEFAULT_KEY_NAME:	    replace-me
