---
platform: linux
image: docker:///boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-src-in
  - name: stemcell
  - name: bats
run:
  path: bosh-cpi-src-in/ci/tasks/run-dynamic-networking-bats.sh
params:
  bats_vm_floating_ip:                       replace-me
  bosh_director_public_ip:                   replace-me
  desired_vcap_user_password:                replace-me
  openstack_flavor_with_ephemeral_disk:      replace-me
  openstack_flavor_with_no_ephemeral_disk:   replace-me
  openstack_security_group:                  replace-me
  primary_network_id:                        replace-me
  private_key_data:                          replace-me
  stemcell_name:                             replace-me
