---
platform: linux
image: docker:///bosh/openstack-cpi-release
inputs:
  - name: bosh-cpi-release
  - name: stemcell
  - name: bosh-concourse-ci
  - name: bats
run:
  path: bosh-cpi-release/ci/tasks/run-dynamic-networking-bats.sh
params:
  bat_stemcell_name:                            replace-me
  bats_private_key_data:                        replace-me
  openstack_bats_flavor_with_ephemeral_disk:    replace-me
  openstack_bats_flavor_with_no_ephemeral_disk: replace-me
  openstack_bat_security_group:                 replace-me
  openstack_bats_network_id:                    replace-me
  bosh_director_public_ip:                      replace-me
  desired_vcap_user_password:                   replace-me
