---
platform: linux
image: docker:///bosh/openstack-cpi-release
inputs:
  - name: bosh-cpi-release
  - name: stemcell
  - name: bosh-concourse-ci
  - name: bats
run:
  path: bosh-cpi-release/ci/tasks/run-manual-networking-bats.sh
params:
  bat_stemcell_name:                            replace-me 
  openstack_bat_security_group:                 replace-me 
  openstack_bats_default_network_id:            replace-me 
  openstack_bats_flavor_with_ephemeral_disk:    replace-me 
  openstack_bats_flavor_with_no_ephemeral_disk: replace-me 
  openstack_bats_second_network_id:             replace-me 
  BAT_CIDR:                                     replace-me 
  BAT_SECOND_CIDR:                              replace-me 
  BAT_DNS_HOST:	                                replace-me
  BAT_INFRASTRUCTURE:	                          replace-me
  BAT_NETWORKING:                               replace-me
  BAT_VCAP_PASSWORD:	                          replace-me
  BAT_DIRECTOR:                                 replace-me 
  BAT_GATEWAY:                                  replace-me 
  BAT_SECOND_GATEWAY:                           replace-me 
  BAT_STATIC_RANGE:                             replace-me 
  BAT_VCAP_PRIVATE_KEY:                         replace-me 
  BAT_VM_FLOATING_IP:                           replace-me 
  BOSH_OPENSTACK_MANUAL_IP:                     replace-me 
  BOSH_OPENSTACK_SECOND_MANUAL_IP:              replace-me 
