---
platform: linux
image: docker:///boshcpi/openstack-cpi-release
inputs:
- name: bosh-cpi-release
- name: bosh-cpi-dev-artifacts
- name: director-state-file
- name: director-manifest
- name: bosh-init
- name: stemcell
- name: bosh-release
- name: version-semver
run:
  path: bosh-cpi-release/ci/tasks/teardown-director.sh
params:
  director-state-file:    replace-me
  director-manifest-file: replace-me
