---
platform: linux
image: docker:///boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-release
  - name: bosh-cpi-dev-artifacts
  - name: director-state-file
  - name: director-manifest-file
  - name: bosh-init
  - name: stemcell
  - name: bosh-release
  - name: version-semver
outputs:
  - name: teardown
run:
  path: bosh-cpi-release/ci/tasks/teardown-director.sh
params:
  bosh_director_ip:        replace-me
  director_state_file:     replace-me
  director_manifest_file:  replace-me
